Here we implement an Artificial Neural network form scratch without any predefined libraries

Regression Problem

In [154]:
import numpy as np
import pandas as pd
import random

df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

df


cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [155]:
def initialize_params(weights):
    wei1=np.full((weights[0],weights[1]),0.01)
    bias1=np.zeros(weights[1])
    wei2=np.full((weights[1],weights[2]),0.01)
    bias2=np.zeros(weights[2])
    return wei1,bias1,wei2,bias2

In [156]:
w1,b1,w2,b2=initialize_params([2,2,1])

In [157]:
b2[0]

0.0

In [158]:
def fwd_propagation(X,w,b):
    layer1_op=np.dot(w.T,X)+b
    return layer1_op

In [159]:
def MSE(y,y_hat):
    return (y-y_hat[0][0])**2

In [160]:
df1=df.iloc[:,0:2]
Y=df.iloc[:,-1]
df1 = (df1 - df1.mean()) / df1.std()
df1

cgpa  profile_score
0  1.161895      -1.024695
1  0.387298      -0.439155
2 -0.387298       0.146385
3 -1.161895       1.317465

In [161]:
df2=np.array(df1)
df2

array([[ 1.161895  , -1.02469508],
       [ 0.38729833, -0.43915503],
       [-0.38729833,  0.14638501],
       [-1.161895  ,  1.3174651 ]])

In [162]:
def update_weights(y,y_hat,j,op1):
    #print(b2[0])
    b2[0]=b2[0]+0.01*2*(y-y_hat[0][0])
    #print(y_hat[0][0])
    w2[0][0]=w2[0][0]+1e-4*2*(y-y_hat[0][0])*op1[0][0]
    w2[1][0]=w2[1][0]+1e-4*2*(y-y_hat[0][0])*op1[1][0]
    w1[0][0]=w1[0][0]+1e-4*2*(y-y_hat[0][0])*w2[0][0]*df2[j][0]#w11
    w1[0][1]=w1[0][1]+1e-4*2*(y-y_hat[0][0])*w2[1][0]*df2[j][0]#w12
    w1[1][0]=w1[1][0]+1e-4*2*(y-y_hat[0][0])*w2[0][0]*df2[j][1]#w21
    w1[1][1]=w1[1][1]+1e-4*2*(y-y_hat[0][0])*w2[1][0]*df2[j][1]#w22
    b1[0]=b1[0]+1e-4*2*(y-y_hat[0][0])*w2[0][0]#b11
    b1[1]=b1[1]+1e-4*2*(y-y_hat[0][0])*w2[1][0]#b22
    
    

In [164]:
for i in range(0,10000):
    loss=0;
    for j in range(0,df2.shape[0]):
        idx=random.randint(0,df2.shape[0]-1)
        op1=fwd_propagation(df2[idx].reshape(2,1),w1,b1.reshape(2,1))
        #print(op1)
        y_hat=fwd_propagation(op1,w2,b2.reshape(1,1))
        #print(y_hat)
        loss=loss+MSE(Y[idx],y_hat)
        update_weights(Y[idx],y_hat,idx,op1)
    print("epoch: ",i,loss//df2.shape[0])
        

epoch:  0 0.0
epoch:  1 0.0
epoch:  2 0.0
epoch:  3 0.0
epoch:  4 0.0
epoch:  5 0.0
epoch:  6 0.0
epoch:  7 0.0
epoch:  8 0.0
epoch:  9 0.0
epoch:  10 0.0
epoch:  11 0.0
epoch:  12 0.0
epoch:  13 0.0
epoch:  14 0.0
epoch:  15 0.0
epoch:  16 0.0
epoch:  17 0.0
epoch:  18 0.0
epoch:  19 0.0
epoch:  20 0.0
epoch:  21 0.0
epoch:  22 0.0
epoch:  23 0.0
epoch:  24 0.0
epoch:  25 0.0
epoch:  26 0.0
epoch:  27 0.0
epoch:  28 0.0
epoch:  29 0.0
epoch:  30 0.0
epoch:  31 0.0
epoch:  32 0.0
epoch:  33 0.0
epoch:  34 0.0
epoch:  35 0.0
epoch:  36 0.0
epoch:  37 0.0
epoch:  38 0.0
epoch:  39 0.0
epoch:  40 0.0
epoch:  41 0.0
epoch:  42 0.0
epoch:  43 0.0
epoch:  44 0.0
epoch:  45 0.0
epoch:  46 0.0
epoch:  47 0.0
epoch:  48 0.0
epoch:  49 0.0
epoch:  50 0.0
epoch:  51 0.0
epoch:  52 0.0
epoch:  53 0.0
epoch:  54 0.0
epoch:  55 0.0
epoch:  56 0.0
epoch:  57 0.0
epoch:  58 0.0
epoch:  59 0.0
epoch:  60 0.0
epoch:  61 0.0
epoch:  62 0.0
epoch:  63 0.0
epoch:  64 0.0
epoch:  65 0.0
epoch:  66 0.0
epoch

In [165]:
w1

array([[-0.53526746, -0.53526746],
       [ 0.41737461,  0.41737461]])

In [166]:
ll=fwd_propagation(df2[3],w1,b1)

In [167]:
fwd_propagation(ll,w2,b2)

array([7.09523693])